# Generated by Django 6.0.1 on 2026-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('WAITER', 'Waiter'), ('KITCHEN_STAFF', 'Kitchen_Staff')], default='WAITER', max_length=20),
        ),
    ]
