# Generated by Django 6.0.1 on 2026-01-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.CharField(blank=True, default='test', max_length=10),
        ),
    ]
