# Generated by Django 6.0.1 on 2026-01-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_field',
        ),
    ]
