# Generated by Django 6.0.1 on 2026-01-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_branch_user_branch_productcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BRANCH_MANAGER', 'Branch Manager'), ('WAITER', 'Waiter'), ('COUNTER', 'Counter'), ('KITCHEN', 'Kitchen')], default='WAITER', max_length=20),
        ),
    ]
