# Generated by Django 6.0.1 on 2026-01-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.productcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('BRANCH_MANAGER', 'Branch Manager'), ('WAITER', 'Waiter'), ('COUNTER', 'Counter'), ('KITCHEN', 'Kitchen')], default='WAITER', max_length=20),
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
