# Generated by Django 6.0.1 on 2026-01-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_unique_together_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BRANCH_MANAGER', 'Branch Manager'), ('WAITER', 'Waiter'), ('COUNTER', 'Counter'), ('KITCHEN', 'Kitchen')], default='WAITER', max_length=20),
        ),
    ]
