# Generated by Django 5.2.10 on 2026-01-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_branch_id_alter_product_id_and_more'),
        ('api', '0010_product_is_available'),
    ]

    operations = [
    ]
