# Generated by Django 6.0.1 on 2026-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_branch_id_alter_customer_id_alter_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
