# Generated by Django 6.0.1 on 2026-02-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_invoice_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='order_status',
            new_name='invoice_status',
        ),
    ]
