# Generated by Django 5.2.10 on 2026-02-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_branch_id_alter_customer_id_alter_invoice_id_and_more'),
        ('api', '0022_rename_order_status_invoice_invoice_status'),
    ]

    operations = [
    ]
