# Generated by Django 5.2.10 on 2026-02-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_invoice_invoice_status'),
        ('api', '0027_alter_payment_payment_method_and_more'),
    ]

    operations = [
    ]
