# Generated by Django 6.0.1 on 2026-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_branch_id_alter_customer_id_alter_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
