# Generated by Django 6.0.1 on 2026-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_table_table_no_alter_table_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='table_count',
            field=models.IntegerField(default=1),
        ),
    ]
