# Generated by Django 6.0.1 on 2026-02-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_branch_table_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='table_count',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_no',
        ),
        migrations.AddField(
            model_name='table',
            name='table_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_branch', to='api.branch'),
        ),
    ]
