# Generated by Django 6.0.1 on 2026-02-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_branch_table_count_remove_table_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_branch', to='api.branch'),
        ),
    ]
