# Generated by Django 6.0.1 on 2026-02-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_table_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='branch',
        ),
    ]
