# Generated by Django 6.0.1 on 2026-02-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_table_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table_branch', to='api.branch'),
            preserve_default=False,
        ),
    ]
