# Generated by Django 6.0.1 on 2026-02-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_table_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_branch', to='api.branch'),
        ),
    ]
