# Generated by Django 6.0.1 on 2026-02-10 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_branch_id_alter_customer_id_alter_invoice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('types', models.CharField(choices=[('ADD_STOCK', 'Cash'), ('REDUCE_STOCK', 'Card')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_inovoice', to='api.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_product', to='api.product')),
            ],
        ),
    ]
