# Generated by Django 6.0.1 on 2026-02-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_itemactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactivity',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_inovoice', to='api.invoice'),
        ),
        migrations.AlterField(
            model_name='itemactivity',
            name='types',
            field=models.CharField(choices=[('ADD_STOCK', 'Add Stock'), ('REDUCE_STOCK', 'Reduce Stock')], max_length=50),
        ),
    ]
