# Generated by Django 6.0.1 on 2026-02-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_itemactivity_invoice_alter_itemactivity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactivity',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_inovoice', to='api.invoice'),
        ),
        migrations.AlterField(
            model_name='itemactivity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_product', to='api.product'),
        ),
    ]
