# Generated by Django 6.0.1 on 2026-02-11 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_itemactivity_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactivity',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='to_product', to='api.product'),
            preserve_default=False,
        ),
    ]
