# Generated by Django 6.0.1 on 2026-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_itemactivity_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_order_d_5ae389_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_branch__3c9e3a_idx',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='bill_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('SALE', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice')], default='SALE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='api_invoice_created_2ecffa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', 'created_at'], name='api_invoice_branch__8f7d73_idx'),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
    ]
