# Generated by Django 6.0.1 on 2026-02-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_payment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_description',
            new_name='description',
        ),
    ]
