# Generated by Django 6.0.1 on 2026-02-18 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_floor_delete_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_invoices', to='api.floor'),
        ),
    ]
