# Generated by Django 6.0.1 on 2026-02-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_branch_id_alter_customer_id_alter_floor_id_and_more'),
        ('api', '0056_alter_itemactivity_types'),
    ]

    operations = [
    ]
