# Generated by Django 6.0.2 on 2026-02-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_branch_id_alter_customer_id_alter_floor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.product'),
        ),
    ]
