# Generated by Django 6.0.2 on 2026-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_itemactivity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactivity',
            name='types',
            field=models.CharField(choices=[('ADD_STOCK', 'Add Stock'), ('REDUCE_STOCK', 'Reduce Stock'), ('EDIT_STOCK', 'Edit Stock')], max_length=50),
        ),
    ]
