# Generated by Django 6.0.1 on 2026-02-23 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='received_by_counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_received_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received_by_waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_received_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
