# Generated by Django 6.0.1 on 2026-02-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_invoice_received_by_counter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'branch')},
        ),
    ]
