# Generated by Django 6.0.1 on 2026-02-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_product_unique_together_product_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category', 'branch')},
        ),
    ]
