# Generated by Django 6.0.1 on 2026-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_product_unique_together'),
        ('api', '0068_alter_payment_payment_method'),
    ]

    operations = [
    ]
