# Generated by Django 6.0.1 on 2026-03-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_merge_20260226_1627'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='unique_customer_per_branch'),
        ),
    ]
